version: "3.8"
services:

  elastic-01:
    image: elasticsearch:8.5.3
    container_name: elastic-01
    restart: on-failure
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

  kibana-01:
    image: kibana:8.5.3
    container_name: kibana-01
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-01:9200
    ports:
      - "5601:5601"
    depends_on:
      - elastic-01
    networks:
      - elastic
    healthcheck:
      test: [ "CMD", "curl", "-f", "kibana-01:5601" ]
      interval: 60s
      timeout: 60s
      retries: 5

  logstash-01:
    container_name: logstash-01
    image: logstash:8.5.3
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    restart: on-failure
    depends_on:
      elastic-01:
        condition: service_started

  zookeeper-01:
    image: zookeeper:latest
    restart: on-failure
    container_name: zookeeper-01
    hostname: zookeeper-01
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1

  kafka-01:
    image: wurstmeister/kafka:latest
    container_name: kafka-01
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-01:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-01:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  kafka-manager-01:
    image: hlebalbau/kafka-manager:stable
    container_name: kafka-manager-01
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper-01:2181"
      APPLICATION_SECRET: "random-secret"
    command:
      - Dpidfile.path=/dev/null

networks:
  elastic:
    name:
      elastic

volumes:
  elasticsearch-data: