version: "3.8"
services:

  logstash:
    container_name: logstash
    image: logstash:7.10.1
    env_file:
      - .env
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    restart: on-failure
    depends_on:
      kafka:
        condition: service_started
    networks:
      - kafka_network

  zookeeper:
    image: zookeeper:latest
    restart: on-failure
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1

  kafka:
    networks:
      - kafka_network
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
      - "9093:9093"
    restart: always
    env_file:
      - .env
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=${HOST_IP}:2181
      - KAFKA_ADVERTISED_HOST_NAME=${HOST_IP}
      - JMX_PORT=9093
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_LOG_RETENTION_HOURS=1
      - KAFKA_MESSAGE_MAX_BYTES=10000000
      - KAFKA_REPLICA_FETCH_MAX_BYTES=10000000
      - KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS=60000
      - KAFKA_NUM_PARTITIONS=2
      - KAFKA_DELETE_RETENTION_MS=1000

  kafka-manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kafka-manager
    networks:
      - kafka_network
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      ZK_HOSTS: ${HOST_IP}
      APPLICATION_SECRET: "random-secret"
    command:
      - Dpidfile.path=/dev/null

networks:
  kafka_network:
    name:
      kafka_network
