version: "3.8"
services:

  logstash-01:
    image: logstash:7.10.1
    env_file:
      - .env
    ports:
      - "5959:5959"
    container_name: logstash-01
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro