version: "3.8"
services:

  metricbeat:
    build: .
    container_name: metricbeat
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redis:
    image: redis:7.0.1
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 50

  elasticsearch:
    image: elasticsearch:8.5.3
    container_name: elasticsearch
    restart: on-failure
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:8.5.3
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    healthcheck:
      test: [ "CMD", "curl", "-f", "kibana:5601" ]
      interval: 60s
      timeout: 60s
      retries: 5
