version: "3.8"
services:

#  java_app:
#    image: febbweiss/java-log-generator:latest
#    depends_on:
#      - es-node-01
#      - kibana-01
#    networks:
#      - elastic

  nginx:
    container_name: nginx
    ports:
      - "80:80"
    image: nginx:latest
    networks:
      - elastic
    healthcheck:
      test: [ "CMD", "curl", "-f", "nginx:80" ]
      interval: 10s
      timeout: 10s
      retries: 5

  logstash:
    container_name: logstash
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    image: logstash:7.10.1
    #command:
    #  - logstash --setup && logstash -f /usr/share/logstash/pipeline/logstash.conf
    env_file:
      - .env
    networks:
      - elastic

  filebeat:
    user: root
    container_name: filebeat
    command: --strict.perms=false
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    image: 'docker.elastic.co/beats/filebeat:7.17.0'
    networks:
      - elastic

networks:
  elastic:
    name: elastic